fix(step-generation): add Python `-> None` type annotation to `def run()` (#18230)
# Overview

Some users (like us) have strict type checking for Python, which
complains about the `def run()` function our generated Python code:
```
error: Function is missing a return type annotation  [no-untyped-def]
```

So this PR changes the declaration to:
```
def run(protocol: protocol_api.ProtocolContext) -> None:
```

This will be helpful for users who want to integrate our generated code
into a bigger Python project.

## Test Plan and Hands on Testing

Updated unit tests.

## Risk assessment

Low.