fix(api): Accessing labware in waste chute raises more descriptive error (#19684)
# Overview

Accessing labware in waste chute raises an error to tell you that it is
in the waste chute, rather than just `offDeck`

## Test Plan and Hands on Testing

Simulated the following protocol:

```
"""Test error messages for waste chute interaction."""
from opentrons import protocol_api

requirements = {"robotType": "Flex", "apiLevel": "2.25"}
# set true to test labware waste chute error handling, set false to test pipetting
test_labware = True

def run(protocol: protocol_api.ProtocolContext) -> None:
    """Test error messages for labware going into waste chute."""
    tiprack1 = protocol.load_labware(
        load_name="opentrons_flex_96_tiprack_1000ul", location="A3"
    )
    tiprack2 = protocol.load_labware(
        load_name="opentrons_flex_96_tiprack_1000ul", location="A2"
    )
    pipette = protocol.load_instrument(
        instrument_name="flex_1channel_1000",
        mount="left",
        tip_racks=[tiprack1, tiprack2],
    )
    chute = protocol.load_waste_chute()
    if test_labware:
        """This will print out Error 4000 GENERAL_ERROR (ProtocolCommandFailedError):
        LabwareMovementNotAllowedError: Labware movements out of the waste chute
        are not supported using the gripper.
        """
        plate = protocol.load_labware(
            load_name="opentrons_96_wellplate_200ul_pcr_full_skirt", location="D1"
        )
        protocol.move_labware(plate, chute, use_gripper=True)
        protocol.move_labware(tiprack2, chute, use_gripper=True)
        protocol.move_labware(plate, "D2", use_gripper=True)
    """This will print out 'Error 4000 GENERAL_ERROR (LabwareNotOnDeckError):
    Cannot access Opentrons Flex 96 Tip Rack 1000 µL because it is the waste chute.'
    """
    pipette.pick_up_tip()
    pipette.drop_tip()
    protocol.move_labware(tiprack1, chute, use_gripper=False)
    pipette.pick_up_tip()
```

now raises `LocationNotAccessibleByPipetteError: Cannot move pipette to
opentrons_flex_96_tiprack_1000ul because it is in the waste chute` if
the pipette tries to access a tip rack in the waste chute vs
`(InvalidLabwarePositionError): Cannot get ancestor slot of location
offDeck`

and also raises `LabwareMovementNotAllowedError: Cannot move
opentrons_96_wellplate_200ul_pcr_full_skirt from the waste chute using
the gripper` if a user tries to access a labware in the trash vs
`LabwareMovementNotAllowedError: Off-deck labware movements are not
supported using the gripper`

I also simulated protocols in `abr-testing` to ensure no other behavior
was altered.

## Changelog

- Moving labware to the wasteChute now returns an addressableArea rather
than an OFF_DECK location so that the error message can be more
descriptive.
- If a labware is in the waste chute, it returns the height as 0 so that
the engine doesn't think that the labware in the waste chute is the
tallest object.
Closes EXEC-349