chore(js): Upgrade jsdom 26 -> 29 (#22132)
## Overview

This is an annoying PR, sorry. It unblocks #22130.

In #22130, I had the innocent dream of writing a CSS selector with
`:has()`. This caused a handful of tests to blow up with obscure errors
like:

```
SyntaxError: 'form,,:r0,,._fields_container_af4dc2 input:disabled' is not a valid selector
```

This was apparently because of bugs in our old jsdom's old CSS selector
engine. Upgrading fixes it—In jsdom 27, they switched their CSS selector
engine from [nwsapi](https://www.npmjs.com/nwsapi) to
[@asamuzakjp/dom-selector](https://www.npmjs.com/package/@asamuzakjp/dom-selector).

But upgrading also causes a bunch of unrelated tests to fail. We have to
modernize them to keep them passing.

## Changelog

You can view this commit-by-commit, but, in short:

* We were firing raw `click` events. Per react-testing-library's
[recommendation](https://testing-library.com/docs/user-event/intro/),
this PR switches us to the higher-level `userEvent` interface.
`userEvent` fires many raw events for a given higher-level user action,
more closely mimicking the browser.

We need to do this now because the jsdom upgrade changed which events
are available in the test environment, which changed which events the
production code listens for.

* A few assertions needed to change because of how jsdom computes and
normalizes styles.

## Test Plan and Hands on Testing

* [x] `CheckboxField` looks the same as it did before.
* [x] `Skeleton` looks the same as it did before.

These are the only production changes.

## Review requests

In principle, does all of this make sense?

## Risk assessment

Low. Aside from `CheckboxField`, this only affects tests, not production
code.

---------

Co-authored-by: Cursor <cursoragent@cursor.com>