ExceptionInProtocolError: TypeError unexpected keyword argument 'slot.’ on labware example line 27
Fix syntax error  “slot =2” instead of “location = 2” for the well plate loading example on line 27.